package frc.robot.subsystems.Chassis;

import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.BaseStatusSignal;
import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.mechanisms.swerve.LegacySwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathPlannerPath;
import com.pathplanner.lib.path.PathPoint;
import com.pathplanner.lib.pathfinding.Pathfinding;
import com.pathplanner.lib.util.PathPlannerLogging;
import edu.wpi.first.math.MathUsageId;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.util.sendable.Sendable;
import edu.wpi.first.util.sendable.SendableBuilder;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants;
import frc.robot.Constants.DriveConstants;
import frc.robot.Constants.FieldConstants;
import frc.robot.Constants.PoseEstimatorConstants;
import frc.robot.Constants.ShooterConstants;
import frc.robot.Constants.VisionFusion;
import frc.robot.RobotContainer;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.GamePeriodReminder;
import frc.robot.subsystems.SuperStructure;
import frc.robot.subsystems.SuperStructure.IntakeMode;
// import frc.robot.subsystems.Vision.LimelightHelpers;
// import frc.robot.subsystems.Vision.VisionSubsystem;
import frc.robot.util.LocalADStarAK;
import java.util.List;
import java.util.Optional;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;
import org.littletonrobotics.junction.Logger;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements Subsystem so it can easily
 * be used in command-based projects.
 *
 * <p>Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
  private static CommandSwerveDrivetrain instance;

  public static CommandSwerveDrivetrain getInstance() {
    return instance;
  }

  public static final double DRIVE_BASE_RADIUS =
      Math.max(
          Math.max(
              Math.hypot(TunerConstants.FrontLeft.LocationX, TunerConstants.FrontLeft.LocationY),
              Math.hypot(TunerConstants.FrontRight.LocationX, TunerConstants.FrontRight.LocationY)),
          Math.max(
              Math.hypot(TunerConstants.BackLeft.LocationX, TunerConstants.BackLeft.LocationY),
              Math.hypot(TunerConstants.BackRight.LocationX, TunerConstants.BackRight.LocationY)));

  private static final double ROBOT_MASS_KG = 74.088;
  private static final double ROBOT_MOI = 6.883;
  private static final double WHEEL_COF = 2.255;
  private static final RobotConfig PP_CONFIG =
      new RobotConfig(
          ROBOT_MASS_KG,
          ROBOT_MOI,
          new ModuleConfig(
              TunerConstants.FrontLeft.WheelRadius,
              TunerConstants.kSpeedAt12Volts.in(MetersPerSecond),
              WHEEL_COF,
              DCMotor.getKrakenX60Foc(1)
                  .withReduction(TunerConstants.FrontLeft.DriveMotorGearRatio),
              TunerConstants.FrontLeft.SlipCurrent,
              1),
          getModuleTranslations());

  private static final double kSimLoopPeriod = 0.004; // 4 ms

  /** Robot loop period (s); matches 50 Hz robotPeriodic / CommandScheduler. */
  private static final double kLoopPeriodSec = 0.02;

  private Notifier m_simNotifier = null;
  private double m_lastSimTime;

  private final SwerveDriveIOInputsAutoLogged swerveInputs = new SwerveDriveIOInputsAutoLogged();

  /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
  private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
  /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
  private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
  /* Keep track if we've ever applied the operator perspective before or not */
  private boolean m_hasAppliedOperatorPerspective = false;

  /** Swerve request to apply during robot-centric path following and velocity control */
  private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds()
          .withDriveRequestType(com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType.Velocity)
          .withSteerRequestType(com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType.Position);

  private final SwerveRequest.ApplyRobotSpeeds m_driveApplyRobotSpeeds =
      new SwerveRequest.ApplyRobotSpeeds()
          .withDriveRequestType(com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType.Velocity)
          .withSteerRequestType(com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType.Position);

  private final SwerveRequest.SwerveDriveBrake m_brakeRequest =
      new SwerveRequest.SwerveDriveBrake()
          .withDriveRequestType(com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType.Velocity)
          .withSteerRequestType(com.ctre.phoenix6.swerve.SwerveModule.SteerRequestType.Position);
  ;

  private final Field2d field2d = new Field2d();

  private final PIDController xController;
  private final PIDController yController;
  private final ProfiledPIDController thetaController;
  private final ProfiledPIDController fieldCentricAngleController;
  private final PIDController autoAimAngleController;
  private final PIDController trenchAngleController;
  private final PIDController hybridIntakeAngleController;

  private PathPlannerPath trenchPathAtlBlue;
  private PathPlannerPath trenchPathAtrBlue;
  private PathPlannerPath trenchPathAtlRed;
  private PathPlannerPath trenchPathAtrRed;
  private Rotation2d snappedSquareEdge = new Rotation2d();
  private double trenchTraversalSign = 1.0;
  private boolean hybridTrenchControlWarmedUp = false;

  private static final double NORMAL_DRIVE_SUPPLY_CURRENT_LIMIT_A = 60.0;
  private static final double NORMAL_DRIVE_STATOR_CURRENT_LIMIT_A = 60.0;
  private static final double NORMAL_STEER_SUPPLY_CURRENT_LIMIT_A = 50.0;
  private static final double NORMAL_STEER_STATOR_CURRENT_LIMIT_A = 50.0;

  /* Swerve requests to apply during SysId characterization */
  private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization =
      new SwerveRequest.SysIdSwerveTranslation();
  private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization =
      new SwerveRequest.SysIdSwerveSteerGains();
  private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization =
      new SwerveRequest.SysIdSwerveRotation();

  /*
   * SysId routine for characterizing translation. This is used to find PID gains
   * for the drive motors.
   */
  private final SysIdRoutine m_sysIdRoutineTranslation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Reduce dynamic step voltage to 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> setControl(m_translationCharacterization.withVolts(output)), null, this));

  /*
   * SysId routine for characterizing steer. This is used to find PID gains for
   * the steer motors.
   */
  private final SysIdRoutine m_sysIdRoutineSteer =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              null, // Use default ramp rate (1 V/s)
              Volts.of(7), // Use dynamic voltage of 7 V
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdSteer_State", state.toString())),
          new SysIdRoutine.Mechanism(
              volts -> setControl(m_steerCharacterization.withVolts(volts)), null, this));

  /*
   * SysId routine for characterizing rotation.
   * This is used to find PID gains for the FieldCentricFacingAngle
   * HeadingController.
   * See the documentation of SwerveRequest.SysIdSwerveRotation for info on
   * importing the log to SysId.
   */
  private final SysIdRoutine m_sysIdRoutineRotation =
      new SysIdRoutine(
          new SysIdRoutine.Config(
              /* This is in radians per second², but SysId only supports "volts per second" */
              Volts.of(Math.PI / 6).per(Second),
              /* This is in radians per second, but SysId only supports "volts" */
              Volts.of(Math.PI),
              null, // Use default timeout (10 s)
              // Log state with SignalLogger class
              state -> SignalLogger.writeString("SysIdRotation_State", state.toString())),
          new SysIdRoutine.Mechanism(
              output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
              },
              null,
              this));

  /* The SysId routine to test */
  private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants, SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, modules);
    instance = this;
    xController = new PIDController(0, 0, 0);
    yController = new PIDController(0, 0, 0);
    thetaController = new ProfiledPIDController(0, 0, 0, new TrapezoidProfile.Constraints(0, 0));
    initializeAutoMoveToPoseControllers();
    fieldCentricAngleController =
        new ProfiledPIDController(
            DriveConstants.AnglekP,
            0.0,
            DriveConstants.AnglekD,
            new TrapezoidProfile.Constraints(
                DriveConstants.AngleMaxVelocity, DriveConstants.AngleMaxAcceleration));
    fieldCentricAngleController.enableContinuousInput(-Math.PI, Math.PI);
    autoAimAngleController =
        new PIDController(
            DriveConstants.AutoAimAnglekP,
            DriveConstants.AutoAimAnglekI,
            DriveConstants.AutoAimAnglekD);
    autoAimAngleController.enableContinuousInput(-Math.PI, Math.PI);
    trenchAngleController =
        new PIDController(DriveConstants.TrenchAnglekP, 0.0, DriveConstants.TrenchAnglekD);
    trenchAngleController.enableContinuousInput(-Math.PI, Math.PI);
    hybridIntakeAngleController =
        new PIDController(DriveConstants.IntakeAnglekP, 0.0, DriveConstants.IntakeAnglekD);
    hybridIntakeAngleController.enableContinuousInput(-Math.PI, Math.PI);
    SmartDashboard.putData("Field", field2d);
    SmartDashboard.putData(
        "Swerve Drive",
        new Sendable() {
          @Override
          public void initSendable(SendableBuilder builder) {
            builder.setSmartDashboardType("SwerveDrive");
            var modules = getModules();

            builder.addDoubleProperty(
                "Front Left Angle", () -> modules[0].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Left Velocity",
                () -> modules[0].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Front Right Angle", () -> modules[1].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Right Velocity",
                () -> modules[1].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Left Angle", () -> modules[2].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Left Velocity",
                () -> modules[2].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Right Angle", () -> modules[3].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Right Velocity",
                () -> modules[3].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty("Robot Angle", () -> getRotation().getRadians(), null);
          }
        });
    if (Utils.isSimulation() && Constants.currentMode != Constants.Mode.REPLAY) {
      startSimThread();
    }
    configureAutoBuilder();
    loadTrenchPaths();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(drivetrainConstants, odometryUpdateFrequency, modules);
    instance = this;
    xController = new PIDController(0, 0, 0);
    yController = new PIDController(0, 0, 0);
    thetaController = new ProfiledPIDController(0, 0, 0, new TrapezoidProfile.Constraints(0, 0));
    initializeAutoMoveToPoseControllers();
    fieldCentricAngleController =
        new ProfiledPIDController(
            DriveConstants.AnglekP,
            0.0,
            DriveConstants.AnglekD,
            new TrapezoidProfile.Constraints(
                DriveConstants.AngleMaxVelocity, DriveConstants.AngleMaxAcceleration));
    fieldCentricAngleController.enableContinuousInput(-Math.PI, Math.PI);
    autoAimAngleController =
        new PIDController(
            DriveConstants.AutoAimAnglekP,
            DriveConstants.AutoAimAnglekI,
            DriveConstants.AutoAimAnglekD);
    autoAimAngleController.enableContinuousInput(-Math.PI, Math.PI);
    trenchAngleController =
        new PIDController(DriveConstants.TrenchAnglekP, 0.0, DriveConstants.TrenchAnglekD);
    trenchAngleController.enableContinuousInput(-Math.PI, Math.PI);
    hybridIntakeAngleController =
        new PIDController(DriveConstants.IntakeAnglekP, 0.0, DriveConstants.IntakeAnglekD);
    hybridIntakeAngleController.enableContinuousInput(-Math.PI, Math.PI);
    SmartDashboard.putData("Field", field2d);
    SmartDashboard.putData(
        "Swerve Drive",
        new Sendable() {
          @Override
          public void initSendable(SendableBuilder builder) {
            builder.setSmartDashboardType("SwerveDrive");
            var modules = getModules();

            builder.addDoubleProperty(
                "Front Left Angle", () -> modules[0].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Left Velocity",
                () -> modules[0].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Front Right Angle", () -> modules[1].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Right Velocity",
                () -> modules[1].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Left Angle", () -> modules[2].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Left Velocity",
                () -> modules[2].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Right Angle", () -> modules[3].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Right Velocity",
                () -> modules[3].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty("Robot Angle", () -> getRotation().getRadians(), null);
          }
        });
    if (Utils.isSimulation() && Constants.currentMode != Constants.Mode.REPLAY) {
      startSimThread();
    }
    configureAutoBuilder();
    loadTrenchPaths();
  }

  /**
   * Constructs a CTRE SwerveDrivetrain using the specified constants.
   *
   * <p>This constructs the underlying hardware devices, so users should not construct the devices
   * themselves. If they need the devices, they can access them through getters in the classes.
   *
   * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
   * @param odometryUpdateFrequency The frequency to run the odometry loop. If unspecified or set to
   *     0 Hz, this is 250 Hz on CAN FD, and 100 Hz on CAN 2.0.
   * @param odometryStandardDeviation The standard deviation for odometry calculation in the form
   *     [x, y, theta]^T, with units in meters and radians
   * @param visionStandardDeviation The standard deviation for vision calculation in the form [x, y,
   *     theta]^T, with units in meters and radians
   * @param modules Constants for each specific module
   */
  public CommandSwerveDrivetrain(
      SwerveDrivetrainConstants drivetrainConstants,
      double odometryUpdateFrequency,
      Matrix<N3, N1> odometryStandardDeviation,
      Matrix<N3, N1> visionStandardDeviation,
      SwerveModuleConstants<?, ?, ?>... modules) {
    super(
        drivetrainConstants,
        odometryUpdateFrequency,
        odometryStandardDeviation,
        visionStandardDeviation,
        modules);
    instance = this;
    xController = new PIDController(0, 0, 0);
    yController = new PIDController(0, 0, 0);
    thetaController = new ProfiledPIDController(0, 0, 0, new TrapezoidProfile.Constraints(0, 0));
    initializeAutoMoveToPoseControllers();
    fieldCentricAngleController =
        new ProfiledPIDController(
            DriveConstants.AnglekP,
            0.0,
            DriveConstants.AnglekD,
            new TrapezoidProfile.Constraints(
                DriveConstants.AngleMaxVelocity, DriveConstants.AngleMaxAcceleration));
    fieldCentricAngleController.enableContinuousInput(-Math.PI, Math.PI);
    autoAimAngleController =
        new PIDController(
            DriveConstants.AutoAimAnglekP,
            DriveConstants.AutoAimAnglekI,
            DriveConstants.AutoAimAnglekD);
    autoAimAngleController.enableContinuousInput(-Math.PI, Math.PI);
    trenchAngleController =
        new PIDController(DriveConstants.TrenchAnglekP, 0.0, DriveConstants.TrenchAnglekD);
    trenchAngleController.enableContinuousInput(-Math.PI, Math.PI);
    hybridIntakeAngleController =
        new PIDController(DriveConstants.IntakeAnglekP, 0.0, DriveConstants.IntakeAnglekD);
    hybridIntakeAngleController.enableContinuousInput(-Math.PI, Math.PI);
    SmartDashboard.putData("Field", field2d);
    SmartDashboard.putData(
        "Swerve Drive",
        new Sendable() {
          @Override
          public void initSendable(SendableBuilder builder) {
            builder.setSmartDashboardType("SwerveDrive");
            var modules = getModules();

            builder.addDoubleProperty(
                "Front Left Angle", () -> modules[0].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Left Velocity",
                () -> modules[0].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Front Right Angle", () -> modules[1].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Front Right Velocity",
                () -> modules[1].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Left Angle", () -> modules[2].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Left Velocity",
                () -> modules[2].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty(
                "Back Right Angle", () -> modules[3].getCurrentState().angle.getRadians(), null);
            builder.addDoubleProperty(
                "Back Right Velocity",
                () -> modules[3].getCurrentState().speedMetersPerSecond,
                null);

            builder.addDoubleProperty("Robot Angle", () -> getRotation().getRadians(), null);
          }
        });
    if (Utils.isSimulation() && Constants.currentMode != Constants.Mode.REPLAY) {
      startSimThread();
    }
    configureAutoBuilder();
    loadTrenchPaths();
  }

  private void initializeAutoMoveToPoseControllers() {
    xController.setPID(DriveConstants.MoveToXkP, 0.0, DriveConstants.MoveToXkD);
    yController.setPID(DriveConstants.MoveToYkP, 0.0, DriveConstants.MoveToYkD);
    thetaController.setPID(DriveConstants.MoveToThetakP, 0.0, DriveConstants.MoveToThetakD);
    thetaController.enableContinuousInput(-Math.PI, Math.PI);
    thetaController.setConstraints(
        new TrapezoidProfile.Constraints(
            DriveConstants.AngleMaxVelocity, DriveConstants.AngleMaxAcceleration));
    xController.setTolerance(DriveConstants.MoveToPositionToleranceMeters);
    yController.setTolerance(DriveConstants.MoveToPositionToleranceMeters);
    thetaController.setTolerance(
        Units.degreesToRadians(DriveConstants.MoveToAngleToleranceDegrees));
  }

  private void configureAutoBuilder() {
    AutoBuilder.configure(
        this::getPose,
        this::setPose,
        this::getChassisSpeeds,
        (speeds, feedforwards) ->
            setControl(
                m_pathApplyRobotSpeeds
                    .withSpeeds(ChassisSpeeds.discretize(speeds, kLoopPeriodSec))
                    .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                    .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())),
        new PPHolonomicDriveController(
            new PIDConstants(
                DriveConstants.PathPlannerTranslationkP,
                0.0,
                DriveConstants.PathPlannerTranslationkD),
            new PIDConstants(
                DriveConstants.PathPlannerRotationkP, 0.0, DriveConstants.PathPlannerRotationkD)),
        PP_CONFIG,
        () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
        this);
    Pathfinding.setPathfinder(new LocalADStarAK());
    PathPlannerLogging.setLogActivePathCallback(
        (activePath) -> {
          Logger.recordOutput(
              "Odometry/Trajectory", activePath.toArray(new Pose2d[activePath.size()]));
        });
    PathPlannerLogging.setLogTargetPoseCallback(
        (targetPose) -> {
          Logger.recordOutput("Odometry/TrajectorySetpoint", targetPose);
        });
  }

  /**
   * Returns a command that applies the specified control request to this swerve drivetrain.
   *
   * @param request Function returning the request to apply
   * @return Command to run
   */
  public Command applyRequest(Supplier<SwerveRequest> request) {
    return run(() -> this.setControl(request.get()));
  }

  /**
   * Runs the SysId Quasistatic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Quasistatic test
   * @return Command to run
   */
  public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.quasistatic(direction);
  }

  /**
   * Runs the SysId Dynamic test in the given direction for the routine specified by {@link
   * #m_sysIdRoutineToApply}.
   *
   * @param direction Direction of the SysId Dynamic test
   * @return Command to run
   */
  public Command sysIdDynamic(SysIdRoutine.Direction direction) {
    return m_sysIdRoutineToApply.dynamic(direction);
  }

  @Override
  public void periodic() {
    if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
      DriverStation.getAlliance()
          .ifPresent(
              allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation);
                m_hasAppliedOperatorPerspective = true;
              });
    }

    if (DriverStation.isDisabled()) {
      stop();
    }

    processLog();
  }

  public void processLog() {
    if (!Logger.hasReplaySource()) {
      updateSwerveInputs();
    }
    Logger.processInputs("Drive/Swerve", swerveInputs);

    field2d.setRobotPose(getPose());
    Logger.recordOutput("Odometry/Robot", getPose());
    Logger.recordOutput("Drive/ChassisSpeeds", getChassisSpeeds());
    Logger.recordOutput(
        "Drive/Velocity",
        Math.hypot(getChassisSpeeds().vxMetersPerSecond, getChassisSpeeds().vyMetersPerSecond));

    // Log per-module and total chassis power
    double totalDriveCurrentA = 0;
    double totalSteerCurrentA = 0;
    double totalChassisPowerW = 0;
    var modules = getModules();
    // Refresh supply signals for all module motors
    var driveSignals = new BaseStatusSignal[modules.length * 2];
    var steerSignals = new BaseStatusSignal[modules.length * 2];
    for (int i = 0; i < modules.length; i++) {
      driveSignals[i * 2] = modules[i].getDriveMotor().getSupplyCurrent();
      driveSignals[i * 2 + 1] = modules[i].getDriveMotor().getSupplyVoltage();
      steerSignals[i * 2] = modules[i].getSteerMotor().getSupplyCurrent();
      steerSignals[i * 2 + 1] = modules[i].getSteerMotor().getSupplyVoltage();
    }
    BaseStatusSignal.refreshAll(driveSignals);
    BaseStatusSignal.refreshAll(steerSignals);
    for (int i = 0; i < modules.length; i++) {
      var driveMotor = modules[i].getDriveMotor();
      var steerMotor = modules[i].getSteerMotor();
      double driveCurrent = driveMotor.getSupplyCurrent().getValueAsDouble();
      double driveVoltage = driveMotor.getSupplyVoltage().getValueAsDouble();
      double steerCurrent = steerMotor.getSupplyCurrent().getValueAsDouble();
      double steerVoltage = steerMotor.getSupplyVoltage().getValueAsDouble();
      totalDriveCurrentA += driveCurrent;
      totalSteerCurrentA += steerCurrent;
      totalChassisPowerW += driveVoltage * driveCurrent + steerVoltage * steerCurrent;
      Logger.recordOutput("Drive/Module" + i + "/DriveSupplyCurrentA", driveCurrent);
      Logger.recordOutput("Drive/Module" + i + "/SteerSupplyCurrentA", steerCurrent);
      Logger.recordOutput("Drive/Module" + i + "/DrivePowerW", driveVoltage * driveCurrent);
      Logger.recordOutput("Drive/Module" + i + "/SteerPowerW", steerVoltage * steerCurrent);
    }
    Logger.recordOutput("Drive/TotalDriveCurrentA", totalDriveCurrentA);
    Logger.recordOutput("Drive/TotalSteerCurrentA", totalSteerCurrentA);
    Logger.recordOutput("Drive/TotalChassisCurrentA", totalDriveCurrentA + totalSteerCurrentA);
    Logger.recordOutput("Drive/TotalChassisPowerW", totalChassisPowerW);
  }

  private void updateSwerveInputs() {
    swerveInputs.pose = getState().Pose;
    swerveInputs.chassisSpeeds = getState().Speeds;
    swerveInputs.pigeonYawDeg = getPigeon2().getYaw().getValueAsDouble();
    swerveInputs.pigeonPitchDeg = getPigeon2().getPitch().getValueAsDouble();
    swerveInputs.pigeonRollDeg = getPigeon2().getRoll().getValueAsDouble();
    swerveInputs.pigeonYawRateDegPerSec = Math.toDegrees(getChassisSpeeds().omegaRadiansPerSecond);
  }

  public static Translation2d getLinearVelocityMagnitudeFromJoysticks(double x, double y) {
    Translation2d input = new Translation2d(x, y);
    if (input.getNorm() < DriveConstants.TranslationDeadband) {
      return new Translation2d();
    } else {
      double norm = MathUtil.applyDeadband(input.getNorm(), DriveConstants.TranslationDeadband);
      return input.times(1.0 / input.getNorm()).times(Math.pow(norm, 2.0));
    }
  }

  public void runVelocity(ChassisSpeeds speeds) {
    ChassisSpeeds discreteSpeeds = ChassisSpeeds.discretize(speeds, kLoopPeriodSec);
    setControl(m_driveApplyRobotSpeeds.withSpeeds(discreteSpeeds));
    Logger.recordOutput("SwerveChassisSpeeds/Setpoints", discreteSpeeds);
  }

  public void runFieldRelativeVelocity(ChassisSpeeds speeds) {
    runVelocity(ChassisSpeeds.fromFieldRelativeSpeeds(speeds, getRotation()));
  }

  public void driveFieldCentric(
      DoubleSupplier xSupplier, DoubleSupplier ySupplier, DoubleSupplier omegaSupplier) {
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    double omega = MathUtil.applyDeadband(omegaSupplier.getAsDouble(), DriveConstants.Deadband);
    omega = Math.copySign(omega * omega, omega);
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX() * getMaxLinearSpeedMetersPerSec(),
            linearVelocityMagnitude.getY() * getMaxLinearSpeedMetersPerSec(),
            omega * getMaxAngularSpeedRadPerSec());
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
  }

  public void driveRobotCentric(
      DoubleSupplier xSupplier, DoubleSupplier ySupplier, DoubleSupplier omegaSupplier) {
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    double omega = MathUtil.applyDeadband(omegaSupplier.getAsDouble(), DriveConstants.Deadband);
    omega = Math.copySign(omega * omega, omega);
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX() * getMaxLinearSpeedMetersPerSec(),
            linearVelocityMagnitude.getY() * getMaxLinearSpeedMetersPerSec(),
            omega * getMaxAngularSpeedRadPerSec());
    runVelocity(speeds);
  }

  public void driveFieldCentricWithMaxSpeed(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      DoubleSupplier omegaSupplier,
      double maxLinearSpeed,
      double maxAngularSpeed) {
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    double omega = MathUtil.applyDeadband(omegaSupplier.getAsDouble(), DriveConstants.Deadband);
    omega = Math.copySign(omega * omega, omega);
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX() * maxLinearSpeed,
            linearVelocityMagnitude.getY() * maxLinearSpeed,
            omega * maxAngularSpeed);
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
  }

  public void driveFieldCentricAtAngle(
      DoubleSupplier xSupplier, DoubleSupplier ySupplier, Supplier<Rotation2d> rotationSupplier) {
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    double omega =
        fieldCentricAngleController.calculate(
            getRotation().getRadians(), rotationSupplier.get().getRadians());
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX() * getMaxLinearSpeedMetersPerSec(),
            linearVelocityMagnitude.getY() * getMaxLinearSpeedMetersPerSec(),
            omega);
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
  }

  public void runCharacterization(double output) {
    setControl(m_translationCharacterization.withVolts(Volts.of(output)));
  }

  public void stop() {
    runVelocity(new ChassisSpeeds());
  }

  public void stopWithX() {
    setControl(m_brakeRequest);
  }

  public ChassisSpeeds getChassisSpeeds() {
    if (Logger.hasReplaySource()) {
      return swerveInputs.chassisSpeeds;
    }
    return getState().Speeds;
  }

  public double getRobotOmegaRadPerSec() {
    return getChassisSpeeds().omegaRadiansPerSecond;
  }

  public double[] getWheelRadiusCharacterizationPositions() {
    double[] values = new double[4];
    for (int i = 0; i < 4; i++) {
      values[i] =
          getModules()[i].getPosition(true).distanceMeters / TunerConstants.FrontLeft.WheelRadius;
    }
    return values;
  }

  public double getFFCharacterizationVelocity() {
    double output = 0.0;
    for (int i = 0; i < 4; i++) {
      output +=
          Units.radiansToRotations(getModules()[i].getDriveMotor().getVelocity().getValueAsDouble())
              / 4.0;
    }
    return output;
  }

  public Pose2d getPose() {
    if (Logger.hasReplaySource()) {
      return swerveInputs.pose;
    }
    return getState().Pose;
  }

  public Rotation2d getRotation() {
    return getPose().getRotation();
  }

  public static Translation2d getAllianceHubCenter() {
    boolean isBlue =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Blue;
    return isBlue ? FieldConstants.Hub.centerPoint : FieldConstants.Hub.oppCenterPoint;
  }

  public Translation2d getShooterWorldPosition() {
    return getPose().getTranslation().plus(ShooterConstants.ShooterOffset.rotateBy(getRotation()));
  }

  public Translation2d getFieldVelocity() {
    ChassisSpeeds fieldSpeeds =
        ChassisSpeeds.fromRobotRelativeSpeeds(getChassisSpeeds(), getRotation());
    return new Translation2d(fieldSpeeds.vxMetersPerSecond, fieldSpeeds.vyMetersPerSecond);
  }

  public double getDistanceToTarget(Translation2d target) {
    return getShooterWorldPosition().getDistance(target);
  }

  // without speed limit, used for passing which need quick response and no need
  // for accuracy
  public void driveAutoAim(
      DoubleSupplier xSupplier, DoubleSupplier ySupplier, Supplier<Rotation2d> targetRotation) {
    SuperStructure.getInstance().setChassisMode(SuperStructure.ChassisMode.SHOOTING);
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    Rotation2d desired = targetRotation.get();
    double omega = calculateAutoAimOmega(desired);
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX() * getMaxLinearSpeedMetersPerSec(),
            linearVelocityMagnitude.getY() * getMaxLinearSpeedMetersPerSec(),
            omega);
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
  }

  // with speed limit, used for scoring which need accuracy
  public void driveAutoAim(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      Supplier<Rotation2d> targetRotation,
      double maxLinearSpeedMetersPerSec) {
    SuperStructure.getInstance().setChassisMode(SuperStructure.ChassisMode.SHOOTING);
    Translation2d linearVelocityMagnitude =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble());
    Rotation2d desired = targetRotation.get();
    double omega = calculateAutoAimOmega(desired);
    ChassisSpeeds speeds =
        new ChassisSpeeds(
            linearVelocityMagnitude.getX()
                * Math.min(maxLinearSpeedMetersPerSec, getMaxLinearSpeedMetersPerSec()),
            linearVelocityMagnitude.getY()
                * Math.min(maxLinearSpeedMetersPerSec, getMaxLinearSpeedMetersPerSec()),
            omega);
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
  }

  /**
   * Shoot lock: X-config brake by default. When the operator trims heading, switch to
   * zero-translation rotation hold instead of fighting the brake request with velocity.
   */
  public void driveAutoAimWithSpeedLimitorLocked(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      Rotation2d targetRotation,
      boolean operatorTrimmingHeading,
      boolean driverTrimmingTranslation) {
    SuperStructure.getInstance().setChassisMode(SuperStructure.ChassisMode.SHOOTING);
    if (operatorTrimmingHeading
        || driverTrimmingTranslation
        || !MathUtil.isNear(targetRotation.getDegrees(), getRotation().getDegrees(), 1.5)) {
      driveAutoAim(
          xSupplier, ySupplier, () -> targetRotation, getMaxLinearSpeedMetersPerSec() * 0.2);
    } else {
      stopWithX();
    }
  }

  public void driveAutoAimWithSpeedLimit(
      DoubleSupplier xSupplier, DoubleSupplier ySupplier, Rotation2d targetRotation) {
    driveAutoAim(xSupplier, ySupplier, () -> targetRotation, getMaxLinearSpeedMetersPerSec() * 0.2);
  }

  /**
   * Applies the current limits for the given {@link SuperStructure.ChassisMode}.
   *
   * <p>During endgame low-power (match time ≤ 50s), {@code NORMAL} and {@code ATTACKMODE} use the
   * same Aim/SHOOTING limits. {@code SHOOTING} always uses Aim limits, so entering/leaving shoot
   * during endgame does not raise chassis current.
   */
  public void applyChassisModeLimits(SuperStructure.ChassisMode mode) {
    boolean endgameLowPower = GamePeriodReminder.getInstance().isEndgameLowPower();
    switch (mode) {
      case NORMAL:
        if (endgameLowPower) {
          applyAimCurrentLimits();
        } else {
          applyModuleCurrentLimits(
              NORMAL_DRIVE_SUPPLY_CURRENT_LIMIT_A,
              NORMAL_DRIVE_STATOR_CURRENT_LIMIT_A,
              NORMAL_STEER_SUPPLY_CURRENT_LIMIT_A,
              NORMAL_STEER_STATOR_CURRENT_LIMIT_A);
        }
        break;
      case SHOOTING:
        applyAimCurrentLimits();
        break;
      case ATTACKMODE:
        if (endgameLowPower) {
          applyAimCurrentLimits();
        } else {
          applyUnlimitedCurrentLimits();
        }
        break;
    }
  }

  private void applyAimCurrentLimits() {
    applyModuleCurrentLimits(
        DriveConstants.AutoAimDriveSupplyCurrentLimitAmps,
        DriveConstants.AutoAimDriveStatorCurrentLimitAmps,
        DriveConstants.AutoAimSteerSupplyCurrentLimitAmps,
        DriveConstants.AutoAimSteerStatorCurrentLimitAmps);
  }

  private void applyModuleCurrentLimits(
      double driveSupplyCurrentLimitA,
      double driveStatorCurrentLimitA,
      double steerSupplyCurrentLimitA,
      double steerStatorCurrentLimitA) {
    CurrentLimitsConfigs driveLimits =
        new CurrentLimitsConfigs()
            .withSupplyCurrentLimit(Amps.of(driveSupplyCurrentLimitA))
            .withSupplyCurrentLimitEnable(true)
            .withStatorCurrentLimit(Amps.of(driveStatorCurrentLimitA))
            .withStatorCurrentLimitEnable(true);
    CurrentLimitsConfigs steerLimits =
        new CurrentLimitsConfigs()
            .withSupplyCurrentLimit(Amps.of(steerSupplyCurrentLimitA))
            .withSupplyCurrentLimitEnable(true)
            .withStatorCurrentLimit(Amps.of(steerStatorCurrentLimitA))
            .withStatorCurrentLimitEnable(true);
    for (var module : getModules()) {
      module.getDriveMotor().getConfigurator().apply(driveLimits);
      module.getSteerMotor().getConfigurator().apply(steerLimits);
    }
  }

  private void applyUnlimitedCurrentLimits() {
    CurrentLimitsConfigs noLimits =
        new CurrentLimitsConfigs()
            .withSupplyCurrentLimitEnable(false)
            .withStatorCurrentLimitEnable(false);
    for (var module : getModules()) {
      module.getDriveMotor().getConfigurator().apply(noLimits);
      module.getSteerMotor().getConfigurator().apply(noLimits);
    }
  }

  public void setPose(Pose2d pose) {
    resetPose(pose);
  }

  public double getMaxLinearSpeedMetersPerSec() {
    return TunerConstants.kSpeedAt12Volts.in(MetersPerSecond);
  }

  public double getMaxAngularSpeedRadPerSec() {
    return getMaxLinearSpeedMetersPerSec() / DRIVE_BASE_RADIUS;
  }

  public static Translation2d[] getModuleTranslations() {
    return new Translation2d[] {
      new Translation2d(TunerConstants.FrontLeft.LocationX, TunerConstants.FrontLeft.LocationY),
      new Translation2d(TunerConstants.FrontRight.LocationX, TunerConstants.FrontRight.LocationY),
      new Translation2d(TunerConstants.BackLeft.LocationX, TunerConstants.BackLeft.LocationY),
      new Translation2d(TunerConstants.BackRight.LocationX, TunerConstants.BackRight.LocationY)
    };
  }

  public Command followPPPath(String pathName) {
    return AutoBuilder.followPath(generatePPPath(pathName));
  }

  public PathPlannerPath generatePPPath(String pathName) {
    try {
      return PathPlannerPath.fromPathFile(pathName);
    } catch (Exception e) {
      e.printStackTrace();
      return null;
    }
  }

  public void autoMoveToPose(Pose2d targetPose) {
    Pose2d currentPose = getPose();
    double xVelocity = xController.calculate(currentPose.getX(), targetPose.getX());
    double yVelocity = yController.calculate(currentPose.getY(), targetPose.getY());
    double omega =
        thetaController.calculate(
            currentPose.getRotation().getRadians(), targetPose.getRotation().getRadians());
    Translation2d linear = new Translation2d(xVelocity, yVelocity);
    double maxV = getMaxLinearSpeedMetersPerSec();
    if (linear.getNorm() > maxV) {
      linear = linear.times(maxV / linear.getNorm());
    }
    Logger.recordOutput("Drive/AutoMoveToPose/Target", targetPose);
    Logger.recordOutput(
        "AutoMoveToPose/CommandedSpeeds", new ChassisSpeeds(linear.getX(), linear.getY(), omega));
    if (atTargetPose()) {
      stop();
      return;
    }
    runFieldRelativeVelocity(new ChassisSpeeds(linear.getX(), linear.getY(), omega));
  }

  public boolean atTargetPose() {
    return xController.atSetpoint() && yController.atSetpoint() && thetaController.atGoal();
  }

  private void loadTrenchPaths() {
    trenchPathAtlBlue = generatePPPath(TrenchLane.ATLtoNTL.pathName);
    trenchPathAtrBlue = generatePPPath(TrenchLane.ATRtoNTR.pathName);
    trenchPathAtlRed = trenchPathAtlBlue != null ? trenchPathAtlBlue.flipPath() : null;
    trenchPathAtrRed = trenchPathAtrBlue != null ? trenchPathAtrBlue.flipPath() : null;
  }

  private static boolean trenchPathsFlippedForPose(Pose2d robotPose) {
    return robotPose.getTranslation().getX() >= FieldConstants.LinesVertical.center;
  }

  private static boolean isRedAlliance() {
    return DriverStation.getAlliance().isPresent()
        && DriverStation.getAlliance().get() == Alliance.Red;
  }

  public void driveHybridTrench(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      DoubleSupplier omegaSupplier,
      double maxLinearSpeed,
      double maxAngularSpeed) {
    driveHybridTrench(xSupplier, ySupplier, omegaSupplier, maxLinearSpeed, maxAngularSpeed, true);
  }

  private void driveHybridTrench(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      DoubleSupplier omegaSupplier,
      double maxLinearSpeed,
      double maxAngularSpeed,
      boolean applySetpoints) {
    IntakeMode intakeMode = SuperStructure.getInstance().getIntakeMode();
    double xInput = xSupplier.getAsDouble();
    double yInput = ySupplier.getAsDouble();
    boolean driverHasInput =
        MathUtil.applyDeadband(Math.hypot(xInput, yInput), DriveConstants.Deadband) > 0.0;
    Translation2d driverLinear =
        getLinearVelocityMagnitudeFromJoysticks(xInput, yInput).times(maxLinearSpeed);
    double omegaInput =
        MathUtil.applyDeadband(omegaSupplier.getAsDouble(), DriveConstants.Deadband);
    double stickOmega = Math.copySign(omegaInput * omegaInput, omegaInput) * maxAngularSpeed;
    Pose2d robotPose = getPose();
    if (driverHasInput) {
      Translation2d driverForTraversal = isRedAlliance() ? driverLinear.unaryMinus() : driverLinear;
      trenchTraversalSign =
          updateTraversalSignFromDriver(robotPose, driverForTraversal, trenchTraversalSign);
    }
    HybridTrenchReference trenchRef = computeHybridTrenchReference(robotPose, trenchTraversalSign);
    Translation2d fieldLinear = blendDriverInput(driverLinear, trenchRef, false, maxLinearSpeed);
    Rotation2d desiredFacing =
        getDesiredFacingHybridTrench(intakeMode, trenchTraversalSign, robotPose);
    logHybridTrench(trenchRef, desiredFacing, fieldLinear);
    boolean manualRotate = Math.abs(omegaInput) > DriveConstants.Deadband;
    double omega = manualRotate ? stickOmega : calculateTrenchOmega(desiredFacing);
    ChassisSpeeds speeds = new ChassisSpeeds(fieldLinear.getX(), fieldLinear.getY(), omega);
    if (applySetpoints) {
      runVelocity(
          ChassisSpeeds.fromFieldRelativeSpeeds(
              speeds,
              isRedAlliance() ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
    }
  }

  public void driveHybridIntake(
      DoubleSupplier xSupplier,
      DoubleSupplier ySupplier,
      DoubleSupplier omegaSupplier,
      double maxLinearSpeed,
      double maxAngularSpeed) {
    Translation2d driverLinear =
        getLinearVelocityMagnitudeFromJoysticks(xSupplier.getAsDouble(), ySupplier.getAsDouble())
            .times(maxLinearSpeed);
    double omegaInput =
        MathUtil.applyDeadband(omegaSupplier.getAsDouble(), DriveConstants.Deadband);
    double stickOmega = Math.copySign(omegaInput * omegaInput, omegaInput) * maxAngularSpeed;
    Rotation2d desiredFacing = getDesiredFacingHybridIntake(driverLinear, IntakeMode.HYBRID);
    boolean manualRotate = Math.abs(omegaInput) > DriveConstants.Deadband;
    double omega = manualRotate ? stickOmega : calculateHybridIntakeOmega(desiredFacing);
    double kLiner = MathUtil.clamp(Math.cos(hybridIntakeAngleController.getError()), 0., 1.);
    driverLinear = driverLinear.times(kLiner * 0.5 + 0.5);
    ChassisSpeeds speeds = new ChassisSpeeds(driverLinear.getX(), driverLinear.getY(), omega);
    boolean isFlipped =
        DriverStation.getAlliance().isPresent()
            && DriverStation.getAlliance().get() == Alliance.Red;
    runVelocity(
        ChassisSpeeds.fromFieldRelativeSpeeds(
            speeds, isFlipped ? getRotation().plus(new Rotation2d(Math.PI)) : getRotation()));
    Logger.recordOutput("HybridIntake/DesiredFacing", desiredFacing);
    Logger.recordOutput("HybridIntake/FieldLinear", driverLinear);
  }

  private void logHybridTrench(
      HybridTrenchReference ref, Rotation2d desiredFacing, Translation2d fieldLinear) {
    Logger.recordOutput("HybridTrench/PathsFlipped", trenchPathsFlippedForPose(ref.robotPose()));
    Logger.recordOutput("HybridTrench/Lane", ref.lane().name());
    Logger.recordOutput("HybridTrench/PathTraversalSign", ref.pathTraversalSign());
    Logger.recordOutput("HybridTrench/GuidanceVector", ref.guidanceVector());
    Logger.recordOutput(
        "HybridTrench/Lookahead", new Pose2d(ref.lookaheadPoint(), new Rotation2d()));
    Logger.recordOutput("HybridTrench/Nearest", new Pose2d(ref.nearestPoint(), new Rotation2d()));
    Logger.recordOutput("HybridTrench/DesiredChassisHeading", desiredFacing);
    Logger.recordOutput("Drive/DesiredFacing", desiredFacing);
    Logger.recordOutput("Drive/BlendedFieldLinear", fieldLinear);
  }

  private HybridTrenchReference computeHybridTrenchReference(
      Pose2d robotPose, double traversalSign) {
    TrenchLane lane = selectTrenchLane(robotPose);
    PathPlannerPath path = getTrenchPath(lane, robotPose);
    List<PathPoint> points = path.getAllPathPoints();
    int nearestIndex = findNearestPointIndex(robotPose.getTranslation(), points);
    PathPoint nearest = points.get(nearestIndex);
    double distanceAlong = nearest.distanceAlongPath;
    double pathLength = points.get(points.size() - 1).distanceAlongPath;
    double lookaheadDistance =
        MathUtil.clamp(
            distanceAlong + traversalSign * DriveConstants.TrenchLookAheadMeters, 0.0, pathLength);
    Translation2d lookaheadPoint = sampleTranslationAtDistance(points, lookaheadDistance);
    return new HybridTrenchReference(
        lane,
        lookaheadPoint.minus(robotPose.getTranslation()),
        lookaheadPoint,
        nearest.position,
        traversalSign,
        robotPose);
  }

  private double computeInitialTraversalSign(Pose2d robotPose) {
    TrenchLane lane = selectTrenchLane(robotPose);
    PathPlannerPath path = getTrenchPath(lane, robotPose);
    List<PathPoint> points = path.getAllPathPoints();
    int nearestIndex = findNearestPointIndex(robotPose.getTranslation(), points);
    double distanceAlong = points.get(nearestIndex).distanceAlongPath;
    return traversalSignFromGeometry(points, distanceAlong, robotPose);
  }

  private double updateTraversalSignFromDriver(
      Pose2d robotPose, Translation2d driverFieldLinear, double currentSign) {
    TrenchLane lane = selectTrenchLane(robotPose);
    PathPlannerPath path = getTrenchPath(lane, robotPose);
    List<PathPoint> points = path.getAllPathPoints();
    int nearestIndex = findNearestPointIndex(robotPose.getTranslation(), points);
    double distanceAlong = points.get(nearestIndex).distanceAlongPath;
    Translation2d tangent = pathTangentAtDistance(points, distanceAlong);
    if (driverFieldLinear.getNorm() > DriveConstants.TrenchDriveIntentThreshold) {
      Translation2d driverDir = driverFieldLinear.div(driverFieldLinear.getNorm());
      double alongTangent = driverDir.dot(tangent);
      if (alongTangent < -0.1) {
        return -1.0;
      }
      if (alongTangent > 0.1) {
        return 1.0;
      }
    }
    return currentSign;
  }

  private static double traversalSignFromGeometry(
      List<PathPoint> points, double distanceAlong, Pose2d robotPose) {
    double pathLength = points.get(points.size() - 1).distanceAlongPath;
    Translation2d pathStart = points.get(0).position;
    Translation2d pathEnd = points.get(points.size() - 1).position;
    double distToStart = robotPose.getTranslation().getDistance(pathStart);
    double distToEnd = robotPose.getTranslation().getDistance(pathEnd);
    if (distanceAlong < pathLength * 0.35 && distToStart < distToEnd) {
      return 1.0;
    }
    if (distanceAlong > pathLength * 0.65 && distToEnd < distToStart) {
      return -1.0;
    }
    return -1.0;
  }

  private static Translation2d pathTangentAtDistance(List<PathPoint> points, double distanceAlong) {
    double pathLength = points.get(points.size() - 1).distanceAlongPath;
    double eps = DriveConstants.TrenchTangentEpsilon;
    Translation2d ahead =
        sampleTranslationAtDistance(points, Math.min(distanceAlong + eps, pathLength));
    Translation2d behind = sampleTranslationAtDistance(points, Math.max(distanceAlong - eps, 0.0));
    Translation2d tangent = ahead.minus(behind);
    if (tangent.getNorm() < 1e-6) {
      return new Translation2d(1.0, 0.0);
    }
    return tangent.div(tangent.getNorm());
  }

  private TrenchLane selectTrenchLane(Pose2d robotPose) {
    double distAtl = distanceToPath(robotPose, getTrenchPath(TrenchLane.ATLtoNTL, robotPose));
    double distAtr = distanceToPath(robotPose, getTrenchPath(TrenchLane.ATRtoNTR, robotPose));
    return distAtl <= distAtr ? TrenchLane.ATLtoNTL : TrenchLane.ATRtoNTR;
  }

  private double distanceToPath(Pose2d robotPose, PathPlannerPath path) {
    if (path == null) {
      return Double.MAX_VALUE;
    }
    List<PathPoint> points = path.getAllPathPoints();
    int idx = findNearestPointIndex(robotPose.getTranslation(), points);
    return robotPose.getTranslation().getDistance(points.get(idx).position);
  }

  private PathPlannerPath getTrenchPath(TrenchLane lane, Pose2d robotPose) {
    boolean flip = trenchPathsFlippedForPose(robotPose);
    return switch (lane) {
      case ATLtoNTL -> flip ? trenchPathAtlRed : trenchPathAtlBlue;
      case ATRtoNTR -> flip ? trenchPathAtrRed : trenchPathAtrBlue;
    };
  }

  private static int findNearestPointIndex(Translation2d robot, List<PathPoint> points) {
    int best = 0;
    double bestDist = Double.MAX_VALUE;
    for (int i = 0; i < points.size(); i++) {
      double d = robot.getDistance(points.get(i).position);
      if (d < bestDist) {
        bestDist = d;
        best = i;
      }
    }
    return best;
  }

  private static Translation2d sampleTranslationAtDistance(
      List<PathPoint> points, double distanceMeters) {
    if (points.isEmpty()) {
      return new Translation2d();
    }
    if (distanceMeters <= points.get(0).distanceAlongPath) {
      return points.get(0).position;
    }
    PathPoint last = points.get(points.size() - 1);
    if (distanceMeters >= last.distanceAlongPath) {
      return last.position;
    }
    for (int i = 1; i < points.size(); i++) {
      PathPoint a = points.get(i - 1);
      PathPoint b = points.get(i);
      if (distanceMeters <= b.distanceAlongPath) {
        double span = b.distanceAlongPath - a.distanceAlongPath;
        double t = span < 1e-9 ? 0.0 : (distanceMeters - a.distanceAlongPath) / span;
        return a.position.interpolate(b.position, t);
      }
    }
    return last.position;
  }

  private Translation2d blendDriverInput(
      Translation2d driverVelocity,
      HybridTrenchReference ref,
      boolean driverHasInput,
      double maxLinearSpeed) {
    Translation2d guidance = ref.guidanceVector();
    double guidanceNorm = guidance.getNorm();
    if (isRedAlliance()) {
      guidance = guidance.unaryMinus();
    }
    if (!driverHasInput) {
      if (guidanceNorm < 1e-6) {
        return new Translation2d();
      }
      return guidance.div(guidanceNorm).times(maxLinearSpeed);
    }
    double driverNorm = driverVelocity.getNorm();
    if (driverNorm < DriveConstants.TrenchDriveIntentThreshold) {
      return driverVelocity;
    }
    if (guidanceNorm < 1e-6) {
      return driverVelocity;
    }
    Translation2d guidanceDir = guidance.div(guidanceNorm);
    double alignment = driverVelocity.div(driverNorm).dot(guidanceDir);
    double alignment01 =
        MathUtil.clamp(
            (alignment - DriveConstants.TrenchMinAlignment)
                / (1.0 - DriveConstants.TrenchMinAlignment),
            0.0,
            1.0);
    double crossTrack = ref.robotPose().getTranslation().getDistance(ref.nearestPoint());
    double proximity01 =
        MathUtil.clamp(1.0 - crossTrack / DriveConstants.TrenchMaxCrossTrackMeters, 0.0, 1.0);
    double blend01 = alignment01 * proximity01;
    double assistWeight =
        Math.pow(blend01, DriveConstants.TrenchBlendExponent) * DriveConstants.TrenchMaxAssist;
    double alongGuidance = driverVelocity.dot(guidanceDir);
    Translation2d projected = guidanceDir.times(alongGuidance);
    return driverVelocity.interpolate(projected, assistWeight);
  }

  private Rotation2d getDesiredFacingHybridTrench(
      IntakeMode intakeMode, double traversalSign, Pose2d robotPose) {
    if (intakeMode == IntakeMode.HYBRID) {
      return travelHeadingAlongPath(robotPose, traversalSign);
    }
    return snapNearestFieldOrthogonalEdge(getRotation());
  }

  private Rotation2d travelHeadingAlongPath(Pose2d robotPose, double traversalSign) {
    TrenchLane lane = selectTrenchLane(robotPose);
    PathPlannerPath path = getTrenchPath(lane, robotPose);
    List<PathPoint> points = path.getAllPathPoints();
    if (points.isEmpty()) {
      return getRotation();
    }
    int nearestIndex = findNearestPointIndex(robotPose.getTranslation(), points);
    Translation2d tangent =
        pathTangentAtDistance(points, points.get(nearestIndex).distanceAlongPath);
    if (tangent.getNorm() < 1e-6) {
      return getRotation();
    }
    Rotation2d alongPath = new Rotation2d(Math.atan2(tangent.getY(), tangent.getX()));
    return traversalSign >= 0.0 ? alongPath : alongPath.plus(Rotation2d.kPi);
  }

  private Rotation2d getDesiredFacingHybridIntake(
      Translation2d blendedVelocity, IntakeMode intakeMode) {
    if (blendedVelocity.getNorm() < DriveConstants.TrenchDriveIntentThreshold) {
      return intakeMode == IntakeMode.HYBRID ? getRotation() : snappedSquareEdge;
    }
    Rotation2d travelHeading =
        new Rotation2d(Math.atan2(blendedVelocity.getY(), blendedVelocity.getX()));
    if (intakeMode == IntakeMode.HYBRID) {
      if (isRedAlliance()) {
        travelHeading = travelHeading.plus(Rotation2d.kPi);
      }
      return travelHeading;
    }
    return travelHeading;
  }

  private Rotation2d snapNearestFieldOrthogonalEdge(Rotation2d currentHeading) {
    Rotation2d[] options = {
      Rotation2d.kZero, Rotation2d.kCCW_90deg, Rotation2d.k180deg, Rotation2d.kCW_90deg
    };
    Rotation2d bestEdge = options[0];
    double bestCost = Double.MAX_VALUE;
    for (Rotation2d option : options) {
      double cost = Math.abs(currentHeading.minus(option).getRadians());
      if (cost < bestCost) {
        bestCost = cost;
        bestEdge = option;
      }
    }
    if (Math.abs(snappedSquareEdge.minus(bestEdge).getRadians())
        < Units.degreesToRadians(DriveConstants.EdgeSnapHysteresisDeg)) {
      return snappedSquareEdge;
    }
    snappedSquareEdge = bestEdge;
    return snappedSquareEdge;
  }

  public void resetHybridTrenchState() {
    snappedSquareEdge = getRotation();
    trenchTraversalSign = computeInitialTraversalSign(getPose());
  }

  /**
   * One-shot HybridTrench run for A/B testing vs {@link frc.robot.NtTelemetryBootstrap}. Does not
   * call {@link #runVelocity}; zero max speeds so auto-guidance cannot command motion.
   */
  public void warmupHybridTrenchControlLoop() {
    if (hybridTrenchControlWarmedUp) {
      return;
    }
    driveHybridTrench(() -> 0.0, () -> 0.0, () -> 0.0, 0.0, 0.0, false);
    hybridTrenchControlWarmedUp = true;
  }

  private double calculateTrenchOmega(Rotation2d desiredFacing) {
    return trenchAngleController.calculate(getRotation().getRadians(), desiredFacing.getRadians());
  }

  private double calculateHybridIntakeOmega(Rotation2d desiredFacing) {
    return hybridIntakeAngleController.calculate(
        getRotation().getRadians(), desiredFacing.getRadians());
  }

  public double calculateOmega(Rotation2d desiredFacing) {
    return fieldCentricAngleController.calculate(
        getRotation().getRadians(), desiredFacing.getRadians());
  }

  private double calculateAutoAimOmega(Rotation2d desiredFacing) {
    return autoAimAngleController.calculate(getRotation().getRadians(), desiredFacing.getRadians());
  }

  private void startSimThread() {
    m_lastSimTime = Utils.getCurrentTimeSeconds();

    /* Run simulation at a faster rate so PID gains behave more reasonably */
    m_simNotifier =
        new Notifier(
            () -> {
              final double currentTime = Utils.getCurrentTimeSeconds();
              double deltaTime = currentTime - m_lastSimTime;
              m_lastSimTime = currentTime;

              /* use the measured time delta, get battery voltage from WPILib */
              updateSimState(deltaTime, RobotController.getBatteryVoltage());
            });
    m_simNotifier.startPeriodic(kSimLoopPeriod);
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   */
  @Override
  public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
    super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
  }

  /**
   * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
   * while still accounting for measurement noise.
   *
   * <p>Note that the vision measurement standard deviations passed into this method will continue
   * to apply to future measurements until a subsequent call to {@link
   * #setVisionMeasurementStdDevs(Matrix)} or this method.
   *
   * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
   * @param timestampSeconds The timestamp of the vision measurement in seconds.
   * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement in the form
   *     [x, y, theta]^T, with units in meters and radians.
   */
  @Override
  public void addVisionMeasurement(
      Pose2d visionRobotPoseMeters,
      double timestampSeconds,
      Matrix<N3, N1> visionMeasurementStdDevs) {
    super.addVisionMeasurement(
        visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
  }

  /**
   * Return the pose at a given timestamp, if the buffer is not empty.
   *
   * @param timestampSeconds The timestamp of the pose in seconds.
   * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
   */
  @Override
  public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
    return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
  }
}
